INSERT INTO USUARIO(username, password)VALUES('nico','$2a$10$SotYb9UC/J52IdAdFPLhFuKwLGbnGQheWRQ.AU2f/xzAh4TTAyaz.');


INSERT INTO ESTABLECIMIENTO(nombre, descripcion, direccion, telefono, pagina_internet, fecha_registro, tipo_establecimiento, localidad,foto1, foto2, foto3) 
VALUES('La Serenidad', ' La cabaña serena cuenta con hall de recepción, estar, comedor, cocina completa, habitación suite con cama king size, dos sofá cama en el estar, ante baño, baño, hidromasajes doble circular y cochera cubierta privada con parrilla.En su equipamiento se destacan, aire acondicionado f/c, 2 SMART TV LED 42” y Wifi. Servicios: Ropa blanca, servicio de mucama y medialunas en la cabaña, además, contamos con grupo electrógeno que abastece todas las necesidades eléctricas del complejo.', 'San Martin 120', '23123143', 'http://lafacilidad.com.ar', '2015-12-11', 'CABAÑA', 'SIERRA_DE_LA_VENTANA', 'https://sierraserena.com/wp-content/uploads/2019/11/MG_3081f-copia-min-1.jpg','https://media-cdn.tripadvisor.com/media/photo-s/09/4f/a4/a2/sierra-serena.jpg','https://sierraserena.com/wp-content/uploads/2019/11/MG_3165f-copia-min.jpg');

INSERT INTO ESTABLECIMIENTO(nombre, descripcion, direccion, telefono, pagina_internet, fecha_registro, tipo_establecimiento, localidad,foto1, foto2, foto3) 
VALUES('Hotel Gran Sierra', 'Las habitaciones sencillas tienen pisos de madera, Wi-Fi gratis, frigobar, utensilios para preparar té y café, y TV de pantalla plana. Se ofrece servicio a la habitación las 24 horas, todos los días.El desayuno y el estacionamiento son gratuitos. Las comodidades también incluyen espacio para eventos, una piscina cubierta climatizada y un restobar sencillo, además de una tina. Se ofrece servicio de masajes.', 'Av. Roca 13', '6345635', 'https://hotel-gransierra.com.ar/', '2016-3-13', 'HOTEL', 'TORNQUIST', 'https://pix10.agoda.net/hotelImages/124/1246280/1246280_16061017110043391702.jpg?ca=6&ce=1&s=1024x768','https://cf.bstatic.com/xdata/images/hotel/max1024x768/184305239.jpg?k=2d22fe63ae1f8960e057238c98fb436f7bd9f65854e3a5e918607c5cfa1d0a52&o=&hp=1','https://hotel-cristal.com.ar/wp-content/uploads/2021/12/slide2-1024x453.jpg');

INSERT INTO ESTABLECIMIENTO(nombre, descripcion, direccion, telefono, pagina_internet, fecha_registro, tipo_establecimiento, localidad,foto1, foto2, foto3) 
VALUES('Estancia Las Marias', 'Relájate con toda la familia en nuestra casa de campo donde la tranquilidad se respira desde el amanecer… Don Juan se encuentra en el pequeño pueblo de Duggan, a 15 km por autopista de San Antonio de Areco.Sobre camino de tierra con acceso mejorado para dias de lluvia. Tranquilidad Total… La casa tiene ambientes amplios con todas las comodidades para relajarte y disfrutar en familia o con amigos.', 'Ruta 76 km 23', '2342345', 'http://lasmarias.com.ar', '2011-2-10', 'CASA_DE_CAMPO', 'LA_GRUTA', 'https://www.cronista.com/files/image/347/347353/6112a6b24e21c.jpg','https://i.ytimg.com/vi/iibwaJtV9pk/maxresdefault.jpg','https://cf.bstatic.com/xdata/images/hotel/max1024x768/312214408.jpg?k=51043c4f0e14f1d861ada3bf8aee6aa5b66da65aeebd3208d0b4ac7a2817238e&o=&hp=1');
